### PR TITLE
Fix and Update for tasks OT301-27 OT301-35 and OT301-43

### PR DESCRIPTION
**Pull request by lalas155**
OT301-27, OT301-35 and OT301-43 delivered in a single branch to fix the issue on "main".

https://alkemy-labs.atlassian.net/browse/OT301-27?atlOrigin=eyJpIjoiZWYwY2Y1YzkzMzdmNGE0YjgyMmFkNTY4NjBkMDMwZWEiLCJwIjoiaiJ9

https://alkemy-labs.atlassian.net/browse/OT301-35?atlOrigin=eyJpIjoiODEzZGFjMDQ3NGM4NDYxY2EzZTJjNzQ1NDViMjMyZWUiLCJwIjoiaiJ9

https://alkemy-labs.atlassian.net/browse/OT301-43?atlOrigin=eyJpIjoiNzAwYTc2NGU4MmQ4NDIxNmFiNWI2NTg5NjBhYWQ2ZGIiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by fgpalacios** [comment]
Broken DAG: [GGUJFKenedy_dag_etl.py] Invalid timetable expression: Exactly 5 or 6 columns has to be specified for iterator expression.

**Comment by lalas155** [comment]
> 

ese error tira al ejecutar el dag de la universidad de kennedy?

**Comment by fgpalacios** [comment]
schedule_interval='%@hourly',
esto tira error

**Comment by lalas155** [comment]
el error lo tiran ambos dags o solo el de kennedy?

**Comment by lalas155** [comment]
ahi cambie el schedule de hourly por timedelta, espero que no tire error esta vez

**Pull request merged**
